# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8de1ca7bc1df7766edcf84f9b83ff17400793f426d2565be6dac9fa5fcd59a5eb43f2d2c3c747ab4a6c76af70ab1c84c8e3a9bc75e72c0581d2fd0e60a354096

test:
  secret_key_base: 1ac686b0e4d4be6010b0cf9d4fa6ce485834526dce362455602f2893e43531945afd8b76606694d706544e6f8da4f9002e40d1ea788cedbd90ea55fa0f5bdcfd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
